#ifndef COMMON_JAUS_HPP
#define COMMON_JAUS_HPP

const int JAUS_DRIVE_MESSAGE_HEADER_SIZE = 5;
const int JAUS_DRIVE_MESSAGE_PAYLOAD_SIZE = 24;
const int JAUS_DRIVE_MESSAGE_FOOTER_SIZE = 1;
const int JAUS_DRIVE_MESSAGE_TOTAL_SIZE = 30;

const int MOTOR_CONTROLLER_ID = 0x05;

const uint8_t DLE_BYTE = 0xAB;
const uint8_t ETX_BYTE = 0xCD;

const int SET_SPEED_CMD = 0x99;
const int SET_ACTUATORS_CMD = 0xA5;

const int WHEEL_MAGNITUDE_LEFT_INDEX = 4;
const int WHEEL_MAGNITUDE_RIGHT_INDEX = 7;
const int WHEEL_DIRECTION_LEFT_INDEX = 10;
const int WHEEL_DIRECTION_RIGHT_INDEX = 13;

const int ARM_MAGNITUDE_TURNTABLE_INDEX = 16;
const int ARM_MAGNITUDE_SHOULDER_INDEX = 17;
const int ARM_MAGNITUDE_ELBOW_INDEX = 18;
const int ARM_MAGNITUDE_WRIST_INDEX = 19;
const int ARM_MAGNITUDE_CLAWROT_INDEX = 20;
const int ARM_MAGNITUDE_CLAWGRIP_INDEX = 21;
const int ARM_DIRECTION_TURNTABLE_INDEX = 22;
const int ARM_DIRECTION_SHOULDER_INDEX = 23;
const int ARM_DIRECTION_ELBOW_INDEX = 24;
const int ARM_DIRECTION_WRIST_INDEX = 25;
const int ARM_DIRECTION_CLAWROT_INDEX = 26;
const int ARM_DIRECTION_CLAWGRIP_INDEX = 27;

#endif
