#!/bin/bash

# export environment variables
source /usr/share/gazebo/setup.sh
export GAZEBO_PLUGIN_PATH=${GAZEBO_PLUGIN_PATH}:../build
export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:$PWD
export GAZEBO_RESOURCE_PATH=${GAZEBO_RESOURCE_PATH}:$PWD

#gzserver Worlds/simple_hill.world --verbose
gazebo -u Worlds/simple_hill.world --verbose
